#!/bin/sh
# do not use this script in this form, 
# change (especially about authentication part) for meet your requirement..
git_user_name=$1
git_password=$2
GITHUB=https://${git_user_name}:${git_password}@github.com/vietnamworker/dhcplist.git
WORKDIR=$HOME/work/dhcplistup

if [ ! -d $WORKDIR ];then
	git clone $GITHUB $WORKDIR
else
	(cd $WORKDIR;git pull)
fi

cd $WORKDIR
git filter-branch -f --prune-empty --tree-filter 'if [ -e README.md ]; then rm -f README.md; fi' -- --all
git push --force

