#!/bin/bash
# This script constructs the list of DHCP Host Name and their IP Address list.
DBNAME=/var/tmp/dhcpdata.db
TABLENAME=maclist
NETWORKDEVICE=eth0
 
sqlite3 $DBNAME "create table if not exists $TABLENAME (hwaddr primary key, hostname, ipaddr, updtime)"

MYHOST=`hostname`
MYHWADDR=`ifconfig $NETWORKDEVICE | grep HWaddr | sed -e 's/^.*HWaddr //'`
MYIP=`ifconfig $NETWORKDEVICE | grep 'inet addr:' | sed -e 's/^.*inet addr://' | sed -e 's/[ ].*$//'`
now=`date`
sqlite3 $DBNAME "insert or replace into  $TABLENAME (hostname, hwaddr, ipaddr) values (\"$MYHOST\", \"$MYHWADDR\", \"$MYIP\")"

tcpdump -i $NETWORKDEVICE -n port 67 and port 68 -v -l | (
    while true;
    do
        read aline
	if echo $aline | egrep -e '^[0-9]' > /dev/null 2>&1 ;then
# delimiter found
		DHCPMSGOPT=
		IPADDR=
		ETHADDR=
		HOSTNAME=
	else
		if [ "$DHCPMSGOPT" == "" ];then
		    DHCPMSGOPT=`echo $aline | grep 'DHCP-Message Option' | sed -e 's/[ 	]*DHCP-Message Option.*: //'`
		fi
       		if [ "$IPADDR" == "" ];then
       		     IPADDR=`echo $aline | grep 'Your-IP' | sed -e 's/[ 	]*Your-IP[ 	]*//'`
        	fi
                if [ "$IPADDR" == "" ];then
                     IPADDR=`echo $aline | grep 'Requested-IP' | sed -e 's/[    ]*Requested-IP[^:]*: //'`
                fi
                if [ "$IPADDR" == "" ];then
                     IPADDR=`echo $aline | grep 'Client-IP ' | sed -e 's/[ 	]*Client-IP //'`
                fi
        	if [ "$ETHADDR" == "" ];then
        	    ETHADDR=`echo $aline | grep 'Client-Ethernet-Address' | sed -e 's/^[       ]*//' | cut -f 2 -d' ' | sed -e 's/://g' | awk '{print toupper($1)}'`
        	fi
		if [ "$HOSTNAME" == "" ];then
		    HOSTNAME=`echo $aline | grep 'Hostname Option' | sed -e 's/^[       ]*//' | cut -f 6 -d' ' | sed -e 's/"//g'`
		fi
        	if [ "$ETHADDR" != "" -a "$HOSTNAME" != "" ];then
	       	    sqlite3 $DBNAME "insert or replace into  $TABLENAME (hostname, hwaddr) values (\"$HOSTNAME\", \"$ETHADDR\")"
		    echo $DHCPMSGOPT : $ETHADDR : $HOSTNAME
        	fi
		if [ "$ETHADDR" != "" -a "$IPADDR" != "" ];then
        	    now=`date`
		    sqlite3 $DBNAME "update  $TABLENAME set ipaddr = \"$IPADDR\", updtime = \"$now\" where hwaddr = \"$ETHADDR\""
		    echo $DHCPMSGOPT : $ETHADDR : $IPADDR
		fi
	fi
    done
)

